struct label* firstPassing(FILE *p,  int *, int *,int *, int *);
struct external* getExterns(FILE *fptr,struct external **);
int secondPassing(FILE *p, char *, struct label *, struct external *,int *,int,int,int);
void assembleWithTwoPasses(FILE *fptr, char *);
int isEmpty(char *x);
int isComment(char *x);
int validLength(char *x);
int validityCheck(char *x);
int alreadyDeclared(char *x, struct label *);
int getString(char *, int *, int);
int getData(char *, int *,int, int );
int isCommand(char *);
int isInstruction(char *);
int isRegister(char *);
int isImmediate(char *);
int isIndex(char *);
int hasTwoOperands(char *);
int hasOneOperand(char *);
int hasNoOperands(char *);
char * trimBeg(char *);
char * trimEnd(char *);
int wordsForCommand(char *);
int wordsForCommand2(char *,char *);
void newLabel(char *, int, char *, struct label **);
void newExternal(char *, struct external **);
void newEntry(char *, struct entry **);
int labelsAccount(struct label *, struct label *, struct external *);
int entriesAccount(struct label *, struct entry *);
int alreadyIsExternal(char *, struct external *);
int alreadyIsEntry(char *, struct entry *);
int mutualExternAndEntryLabels(struct external *, struct entry *);
void updateDataLabels(struct label *,int);
void printLabels(struct label *);
void printEntries(struct entry *);
